# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://rian010.github.io
baseurl: /
title: YAN's Site
description: >
    YAN's Site | YAN's Site


## => Language and Timezone
##############################
lang: id
timezone: Asia/Makassar


## => Author and Social
##############################
author:
  type      : "person"
  name      : YAN #deuterium
  url       : https://rian010.github.io/
  avatar    : https://avatars.githubusercontent.com/u/89960876?s=96&v=4  #https://github.com/deut-erium/deut-erium.github.io/blob/master/Circle-limit-IV.jpg?raw=1
  bio       : YAN Sites #Breachers from IITB
  email     : mhmmriann@gmail.com #zehrileLaunde@protonmail.com
  facebook  : #groups/csec.iitb # "user_name" the last part of your profile url, e.g. https://www.facebook.com/user_name
  twitter   : #0xdeuterium # "user_name" the last part of your profile url, e.g. https://twitter.com/user_name
  weibo     : # "user_id"   the last part of your profile url, e.g. https://www.weibo.com/user_id/profile?...
  googleplus: # "user_id"   the last part of your profile url, e.g. https://plus.google.com/u/0/user_id
  telegram  : # "user_name" the last part of your profile url, e.g. https://t.me/user_name
  medium    : # "user_name" the last part of your profile url, e.g. https://medium.com/user_name
  zhihu     : # "user_name" the last part of your profile url, e.g. https://www.zhihu.com/people/user_name
  douban    : # "user_name" the last part of your profile url, e.g. https://www.douban.com/people/user_name
  linkedin  : rian010 # "user_name" the last part of your profile url, e.g. https://www.linkedin.com/in/user_name
  github    : rian010 # "user_name" the last part of your profile url, e.g. https://github.com/user_name
  npm       : # "user_name" the last part of your profile url, e.g. https://www.npmjs.com/~user_name



## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: rian010/rian010.github.io
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /blog
  archive: /blog/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 7
paginate_path: /blog/page:num


## => Comments
##############################
comments:
  provider: disqus
  disqus:
    shortname: yan010


## => Pageview
##############################
pageview:
  provider: #leancloud
  leancloud:
    app_id: #uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
    app_key: #Mzf5m9skSwYVWVXhGiYMNyXs
    app_class: #ThomasBlog


## => Analytics
##############################
analytics:
  provider: #google
  google:
    tracking_id: #UA-71907556-1


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001
